#ifndef SNOWFLAKE_DEVICES_H
#define SNOWFLAKE_DEVICES_H

#define DEVICE_OUT 00
#define DEVICE_IN  01
#define DEVICE_PRT 02
#define DEVICE_BTN 03

#define DEVICE_OUT_STRING "OUT"
#define DEVICE_IN_STRING  " IN"
#define DEVICE_PRT_STRING "PRT"
#define DEVICE_BTN_STRING "BTN"

#endif
